#!/bin/bash

dnsRecords=(
    "diagnostics.meethue.com"
    "ws.meethue.com"
    "dc1.philips.com"
)

echo "###############################################################"
echo "# Generated by                                                #"
echo "# https://github.com/janwiesemann/suricata-no-philips-metrics #"
echo "###############################################################"
echo

sid=18109700
for record in "${dnsRecords[@]}"
do :
    echo "###### $record ($sid) ######"
    echo "alert dns any any -> any 53 (msg:\"Philips - $record - DNS request for $record\"; dns_query;  content:\"$record\"; nocase; sid:${sid}0;)"
    echo "alert http any any -> any \$HTTP_PORTS  (msg:\"Philips - $record - HTTP request for $record\"; content:\"$record\"; http_uri; flow:to_server,established; sid:${sid}1;)"
    echo "alert tls any any -> any any (msg:\"Philips - $record - TLS for $record\"; tls_sni; content:\"$record\"; flow:to_server,established; sid:${sid}2;)"
    echo

    ((sid++))
done